import { useParams, Link } from "react-router-dom";
import { ArrowLeft, Printer, Copy } from "lucide-react";
import { toast } from "sonner";
import { useProject, useValidation, useInvestibility, usePivots, useDeck,
  useMatches, useGrantMatches, useBenchmarkLinks } from "@/hooks/useProjects";
import { Button } from "@/components/ui/Button";
import { Skeleton } from "@/components/ui/Card";
import { formatUsd, formatDate, copyToClipboard } from "@/lib/utils";

/**
 * One-click executive pitch book: every module consolidated into a single
 * printable document. Print styles turn it into a clean PDF via the browser.
 */
export default function PitchBook() {
  const { id } = useParams<{ id: string }>();
  const { data: project, isLoading } = useProject(id);
  const { data: validation } = useValidation(id);
  const { data: report } = useInvestibility(id);
  const { data: pivots } = usePivots(id);
  const { data: deck } = useDeck(id);
  const { data: matches } = useMatches(id);
  const { data: grants } = useGrantMatches(id);
  const { data: benchmarks } = useBenchmarkLinks(id);

  if (isLoading) return <Skeleton className="h-96" />;
  if (!project) return <p className="text-ink-mute">Project not found.</p>;

  function toMarkdown() {
    const L: string[] = [`# ${project!.title}`, "", `**Domain:** ${project!.domain?.name}`, ""];
    L.push("## Problem", "", project!.problem_statement, "");
    L.push("## Target user", "", project!.target_persona, "");
    L.push("## Approach", "", project!.technical_approach, "");

    if (validation) {
      L.push("## Validation", "", `**Score:** ${validation.viability_score}/100 (${validation.pain_classification})`, "");
      if (validation.headline) L.push(`> ${validation.headline}`, "");
      if (validation.summary) L.push(validation.summary, "");
      const m = validation.market_sizing;
      if (m?.tam) {
        L.push("### Market size", "");
        (["tam", "sam", "som"] as const).forEach((k) => {
          const leg = m[k];
          if (leg) L.push(`- **${k.toUpperCase()}:** ${leg.display || formatUsd(leg.value_usd)} — ${leg.method}`);
        });
        L.push("");
      }
      validation.sub_scores?.forEach((s) => L.push(`- **${s.label}:** ${s.score}/100 — ${s.reasoning}`));
      L.push("");
    }

    if (report) {
      L.push("## Investment verdict", "", `**${report.verdict_label}** — readiness ${report.readiness_score}/100`, "");
      report.verdict_bullets?.forEach((b) => L.push(`- **${b.title}:** ${b.detail}`));
      if (report.investor_lens) L.push("", `> ${report.investor_lens}`);
      L.push("");
    }

    if (pivots?.length) {
      L.push("## Strategic pivots", "");
      pivots.forEach((p) => {
        L.push(`### ${p.title}${p.adopted ? " (adopted)" : ""}`, "", p.pivot_thesis, "");
        L.push(`- **What changes:** ${p.what_changes}`, `- **New market:** ${p.target_market}`,
          `- **Difficulty:** ${p.difficulty} · projected +${p.expected_score_delta}`, "");
      });
    }

    if (deck?.slides?.length) {
      L.push("## Pitch deck", "");
      if (deck.narrative_summary) L.push(deck.narrative_summary, "");
      deck.slides.forEach((s, i) => {
        L.push(`### ${i + 1}. ${s.title}`, "", `**${s.headline}**`, "");
        s.bullets.forEach((b) => L.push(`- ${b}`));
        L.push("");
      });
    }

    if (matches?.length) {
      L.push("## Investor targets", "");
      matches.forEach((m) => {
        L.push(`- **${m.investor.name}** (fit ${Math.round(m.fit_score)}) — ${m.investor.cheque_display ?? "cheque undisclosed"}`);
        if (m.rationale) L.push(`  - ${m.rationale}`);
      });
      L.push("");
    }

    if (grants?.length) {
      L.push("## Non-dilutive funding", "");
      grants.forEach((g) => {
        L.push(`- **${g.grant.name}** (${g.grant.amount_display}) — fit ${Math.round(g.fit_score)}`);
        if (g.next_step) L.push(`  - Next step: ${g.next_step}`);
      });
      L.push("");
    }

    if (benchmarks?.length) {
      L.push("## Indian benchmarks", "");
      benchmarks.forEach((b) => {
        L.push(`### ${b.benchmark.startup_name} — ${b.benchmark.valuation_display ?? "undisclosed"}`, "",
          b.parallel_analysis, "");
        if (b.lesson) L.push(`**Lesson:** ${b.lesson}`, "");
      });
    }

    L.push("---", "", `Generated by LaunchPad RV · ${formatDate(new Date().toISOString())}`);
    return L.join("\n");
  }

  return (
    <div className="mx-auto max-w-4xl">
      <div className="flex flex-wrap items-center gap-3 print:hidden">
        <Link
          to={`/project/${project.id}`}
          className="flex items-center gap-2 text-[0.8125rem] text-ink-mute transition-colors hover:text-ink"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to workbench
        </Link>
        <div className="ml-auto flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={async () => {
              const ok = await copyToClipboard(toMarkdown());
              toast[ok ? "success" : "error"](ok ? "Pitch book copied as markdown" : "Copy failed");
            }}
          >
            <Copy className="h-3.5 w-3.5" />
            Copy markdown
          </Button>
          <Button size="sm" onClick={() => window.print()}>
            <Printer className="h-3.5 w-3.5" />
            Print / save PDF
          </Button>
        </div>
      </div>

      <article className="mt-8 space-y-10 print:mt-0">
        <header className="border-b border-line pb-6">
          <p className="text-[0.75rem] font-medium tracking-wide text-ink-faint uppercase">
            Executive pitch book · {project.domain?.name}
          </p>
          <h1 className="mt-3 font-display text-3xl font-semibold tracking-tight">{project.title}</h1>
          {validation?.headline && (
            <p className="mt-3 text-base leading-relaxed text-ink-mute">{validation.headline}</p>
          )}
          <div className="mt-5 flex flex-wrap gap-6">
            {validation && (
              <Metric label="Viability" value={`${validation.viability_score}/100`} note={validation.pain_classification} />
            )}
            {report && (
              <Metric label="Readiness" value={`${report.readiness_score}/100`} note={report.verdict_label} />
            )}
            {validation?.market_sizing?.tam && (
              <Metric label="TAM" value={validation.market_sizing.tam.display || formatUsd(validation.tam_usd)} />
            )}
            {validation?.market_sizing?.som && (
              <Metric label="SOM" value={validation.market_sizing.som.display || formatUsd(validation.som_usd)} />
            )}
          </div>
        </header>

        <Section title="The problem">
          <p>{project.problem_statement}</p>
        </Section>
        <Section title="Who it is for">
          <p>{project.target_persona}</p>
        </Section>
        <Section title="How it works">
          <p>{project.technical_approach}</p>
        </Section>

        {validation && (
          <Section title="Validation">
            <p>{validation.summary}</p>
            <div className="mt-4 grid gap-2 sm:grid-cols-2">
              {validation.sub_scores?.map((s) => (
                <div key={s.key} className="rounded-lg border border-line p-3">
                  <div className="flex items-baseline justify-between">
                    <span className="text-[0.8125rem] font-medium text-ink">{s.label}</span>
                    <span className="num text-[0.8125rem] text-ink-mute">{s.score}</span>
                  </div>
                  <p className="mt-1 text-[0.75rem] leading-relaxed text-ink-mute">{s.reasoning}</p>
                </div>
              ))}
            </div>
            {validation.defensibility?.analysis && (
              <>
                <h3 className="mt-6 font-display text-[0.9375rem] font-semibold">Defensibility</h3>
                <p className="mt-1.5">{validation.defensibility.analysis}</p>
              </>
            )}
          </Section>
        )}

        {report && (
          <Section title={`Investment verdict — ${report.verdict_label}`}>
            <ul className="space-y-3">
              {report.verdict_bullets?.map((b, i) => (
                <li key={i}>
                  <span className="font-medium text-ink">{b.title}. </span>
                  {b.detail}
                </li>
              ))}
            </ul>
            {report.investor_lens && <p className="mt-4 italic">{report.investor_lens}</p>}
          </Section>
        )}

        {pivots && pivots.length > 0 && (
          <Section title="Strategic pivots">
            <div className="space-y-4">
              {pivots.map((p) => (
                <div key={p.id} className="rounded-lg border border-line p-4">
                  <p className="font-display text-[0.9375rem] font-semibold text-ink">
                    {p.title}
                    {p.adopted && <span className="ml-2 text-[0.75rem] text-good">adopted</span>}
                  </p>
                  <p className="mt-1.5">{p.pivot_thesis}</p>
                  <p className="mt-2 text-[0.8125rem] text-ink-faint">
                    {p.difficulty} effort · projected +{p.expected_score_delta} points
                  </p>
                </div>
              ))}
            </div>
          </Section>
        )}

        {deck?.slides && deck.slides.length > 0 && (
          <Section title="Pitch deck">
            {deck.narrative_summary && <p className="mb-5">{deck.narrative_summary}</p>}
            <div className="space-y-5">
              {deck.slides.map((s, i) => (
                <div key={s.key} className="break-inside-avoid">
                  <p className="font-display text-[0.9375rem] font-semibold text-ink">
                    {i + 1}. {s.title}
                  </p>
                  <p className="mt-1 text-ink">{s.headline}</p>
                  <ul className="mt-2 space-y-1">
                    {s.bullets.map((b, j) => (
                      <li key={j} className="flex gap-2">
                        <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-ink-faint" />
                        {b}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </Section>
        )}

        {matches && matches.length > 0 && (
          <Section title="Investor targets">
            <div className="space-y-3">
              {matches.slice(0, 8).map((m) => (
                <div key={m.id} className="break-inside-avoid rounded-lg border border-line p-3">
                  <div className="flex flex-wrap items-baseline gap-2">
                    <span className="font-medium text-ink">{m.investor.name}</span>
                    <span className="num text-[0.75rem] text-ink-faint">fit {Math.round(m.fit_score)}</span>
                    {m.investor.cheque_display && (
                      <span className="text-[0.75rem] text-ink-faint">· {m.investor.cheque_display}</span>
                    )}
                  </div>
                  {m.rationale && <p className="mt-1 text-[0.8125rem]">{m.rationale}</p>}
                </div>
              ))}
            </div>
          </Section>
        )}

        {grants && grants.length > 0 && (
          <Section title="Non-dilutive funding">
            <div className="space-y-3">
              {grants.map((g) => (
                <div key={g.id} className="break-inside-avoid rounded-lg border border-line p-3">
                  <div className="flex flex-wrap items-baseline gap-2">
                    <span className="font-medium text-ink">{g.grant.name}</span>
                    <span className="text-[0.75rem] text-ink-faint">{g.grant.amount_display}</span>
                  </div>
                  <p className="mt-1 text-[0.8125rem]">{g.fit_rationale}</p>
                  {g.next_step && (
                    <p className="mt-1 text-[0.8125rem] text-ink">
                      <span className="font-medium">Next step: </span>
                      {g.next_step}
                    </p>
                  )}
                </div>
              ))}
            </div>
          </Section>
        )}

        {benchmarks && benchmarks.length > 0 && (
          <Section title="Indian benchmarks">
            <div className="space-y-4">
              {benchmarks.map((b) => (
                <div key={b.id} className="break-inside-avoid">
                  <p className="font-display text-[0.9375rem] font-semibold text-ink">
                    {b.benchmark.startup_name}
                    {b.benchmark.valuation_display && (
                      <span className="ml-2 text-[0.8125rem] font-normal text-ink-faint">
                        {b.benchmark.valuation_display}
                      </span>
                    )}
                  </p>
                  <p className="mt-1">{b.parallel_analysis}</p>
                  {b.lesson && <p className="mt-1 text-ink"><span className="font-medium">Lesson: </span>{b.lesson}</p>}
                </div>
              ))}
            </div>
          </Section>
        )}

        <footer className="border-t border-line pt-5 text-[0.75rem] text-ink-faint">
          Generated by LaunchPad RV Institutions · {formatDate(new Date().toISOString())}
        </footer>
      </article>
    </div>
  );
}

function Metric({ label, value, note }: { label: string; value: string; note?: string }) {
  return (
    <div>
      <p className="text-[0.6875rem] font-medium tracking-wide text-ink-faint uppercase">{label}</p>
      <p className="num mt-1 text-xl font-semibold text-ink">{value}</p>
      {note && <p className="text-[0.75rem] text-ink-mute">{note}</p>}
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="break-inside-avoid">
      <h2 className="font-display text-xl font-semibold tracking-tight text-ink">{title}</h2>
      <div className="mt-3 text-[0.875rem] leading-relaxed text-ink-mute">{children}</div>
    </section>
  );
}
